<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mjs</string>
	</array>
	<key>name</key>
	<string>Metascript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(''')</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.metascript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(''')</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.metascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.heredoc.metascript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(""")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.metascript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(""")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.metascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.heredoc.metascript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.metascript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.metascript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.metascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.metascript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.metascript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.metascript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(')</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.metascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(abstract|as|boolean|byte|char|class|const|debugger|default|delete|double|enum|export|extends)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.reserved.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(final|float|function|implements|import|in|instanceof|int|interface|is|long)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.reserved.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(namespace|native|package|private|protected|public|short|static|super|synchronized|throws|transient|typeof|use|volatile|with)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.reserved.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(new)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.control.new.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(catch|finally|throw|try)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.control.exception.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(loop|break|continue|while|yield)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.control.repeat.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(give!|next!)</string>
			<key>name</key>
			<string>keyword.control.repeat.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(case|else|if)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.control.conditional.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bdo!</string>
			<key>name</key>
			<string>keyword.control.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(default|do|for|goto|return|switch)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>keyword.control.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(const|var|void|let|fun)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>storage.modifier.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(false)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(null)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>constant.language.null.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(Infinity|NaN|undefined)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>constant.language.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(require|parseInt|parse-int)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>support.function.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0([box])[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?(e[+\-]?[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b)(this)(?![\-&gt;!?])\b</string>
			<key>name</key>
			<string>storage.function.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,)</string>
			<key>name</key>
			<string>meta.delimiter.comma.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.square.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.curly.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#(\p{Word}|[\-&gt;])+[!?]?)</string>
			<key>name</key>
			<string>constant.other.symbol.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((#|\p{Word})(\p{Word}|[\-&gt;])*[!?]?)</string>
			<key>name</key>
			<string>entity.name.metascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([:\.\\+\*\-\/&lt;&gt;\~\|^#@!\?&amp;=`%]+)</string>
			<key>name</key>
			<string>keyword.operator.metascript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.Metascript</string>
	<key>uuid</key>
	<string>8ddea5ae-2731-484e-ae56-858360a74382</string>
</dict>
</plist>
